apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: corrective-drift
  namespace: argocd
spec:
  description: Corrective Drift applications
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

